name: ArcBox
summary: This is a deployment of Azure Arc Jumpstart ArcBox using Bicep.
description: Deploys an instance of ArcBox.
templatePath: main.bicep
parameters:
- id: "flavor"
  name: "The flavor of ArcBox to deploy"
  description: "Amount of memory available to the Container App"
  type: "string"
  default: "ITPro"
  allowed:
    - "DataOps"
    - "DevOps"
    - "ITPro"
runner: Bicep